openapi: "3.1.0"
info:
    version: "1.0.0"
    title: "GreenChoice ZonnepanelenDelen integration"
    description: Enable GreenChoice customer verification, highlighting ZonnepanelenDelen projects in GreenChoice app and interest period payment verifications

paths:
    /customer/{customer_id}/verify:
        parameters:
            - name: customer_id
              description: The unique identifier as a GreenChoice customer
              in: path
              required: true
              schema:
                  $ref: "#/components/schemas/customer_id"
    /zpd/projects/{project_uuid}:
        parameters:
            - name: project_uuid
              description: The unique identifier of a ZonnepanelenDelen project
              in: path
              required: true
              schema:
                  $ref: "#/components/schemas/project_uuid"
    /zpd/projects/{project_uuid}/interest_payment/{interest_payment_uuid}:
        parameters:
            - name: project_uuid
              description: The unique identifier of a ZonnepanelenDelen project
              in: path
              required: true
              schema:
                  $ref: "#/components/schemas/project_uuid/"
            - name: interest_payment_uuid
              description: The unique identifier of an interest payment for a defined period
              in: path
              required: true
              schema:
                  $ref: "#/components/schemas/interest_payment_uuid"
    /spacecrafts/{spacecraftId}:
        parameters:
            - name: spacecraftId
              description: The unique identifier of the spacecraft
              in: path
              required: true
              schema:
                  $ref: "#/components/schemas/SpacecraftId"
        get:
            summary: Read a spacecraft
            responses:
                "200":
                    description: The spacecraft corresponding to the provided `spacecraftId`
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Spacecraft"
                404:
                    description: No spacecraft found for the provided `spacecraftId`
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Error"
                500:
                    description: Unexpected error
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Error"
components:
    schemas:
        customer_id:
            description: The unique identifier as a GreenChoice customer
            type: string
        investor_uuid:
            description: The unique identifier as a ZonnepanelenDelen investor
            type: string
            format: uuid
        project_uuid:
            description: The unique identifier of a ZonnepanelenDelen project
            type: string
            format: uuid
        interest_payment_uuid:
            description: The unique identifier of an interest payment for a defined period
            type: string
            format: uuid
        SpacecraftId:
            description: The unique identifier of a spacecraft
            type: string
        Customer:
            type: object
            required:
                - id
                - investor_uuid
            properties:
                id:
                    $ref: "#/components/schemas/customer_id"
                investor_uuid:
                    $ref: "#/components/schemas/investor_uuid"
        Spacecraft:
            type: object
            required:
                - id
                - name
                - type
            properties:
                id:
                    $ref: "#/components/schemas/SpacecraftId"
                name:
                    type: string
                type:
                    type: string
                    enum:
                        - capsule
                        - probe
                        - satellite
                        - spaceplane
                        - station
                description:
                    type: string
        Error:
            type: object
            required:
                - message
            properties:
                message:
                    description: A human readable error message
                    type: string
    securitySchemes:
        ApiKey:
            type: apiKey
            in: header
            name: X-Api-Key
security:
    - ApiKey: []
